/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "zuxisavlaxiywcingyyb"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eGlzYXZsYXhpeXdjaW5neXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTA0NzIsImV4cCI6MjA2OTM2NjQ3Mn0.y0rYPLiMm61GhC-i88dUNhUgtL41yKwNtHPw9kD0H0w"